# Generated by Django 3.2.2 on 2021-05-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('no_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Duration (in minutes)')),
                ('required_score_to_pass', models.IntegerField(help_text='Passing Score')),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', ' medium'), ('hard', 'hard')], max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
    ]
